# Generated by Django 3.2.5 on 2021-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('name', models.CharField(max_length=50, unique=True)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('personal', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('angel', models.URLField(blank=True)),
                ('crunchbase', models.URLField(blank=True)),
                ('reply', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('followup_sent', models.BooleanField(default=False)),
                ('key', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
