# Generated by Django 3.2.5 on 2021-07-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='personal',
        ),
    ]
