# Generated by Django 3.2.5 on 2021-07-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Targets',
            new_name='Target',
        ),
    ]
