# Generated by Django 3.2.5 on 2021-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_target_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='personal',
            field=models.URLField(blank=True),
        ),
    ]
