# Generated by Django 3.2.5 on 2021-07-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_targets_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
