# Generated by Django 3.2.5 on 2021-07-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_target_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='domain',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
